[workspace]
members = ["app", "logic"]
resolver = '3'

[workspace.dependencies]
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
anyhow = "1.0.100"
thiserror="2.0.18"
chrono = {version = "0.4.43", features = ["serde"]}
